"""Starts a Blender session the MCP server can drive.

    blender --python tools/blender_live.py

Run it WITHOUT --background: the addon's server has to stay alive for something
to connect to, and a background Blender exits as soon as the script returns.

WHY A LIVE BLENDER AT ALL, given the rest of the pipeline is headless. The
headless render is the thing that ships and it should stay that way -
reproducible, in version control, regenerated by one command. This is for the
other half of the job, which headless cannot do: looking at a part from an
angle, checking that a fillet actually followed the edge it was meant to, and
turning a shape over before committing eight minutes to rendering it.

It enables the addon, opens the port and prints what it did, so the whole thing
is one command rather than four clicks in a preferences dialog.
"""

import addon_utils
import bpy

ADDON = "blender_mcp"   # installed by: uvx blender-mcp install-addon
PORT = 9876


def main():
    enabled = [m.__name__ for m in addon_utils.modules() if addon_utils.check(m.__name__)[1]]
    if ADDON not in enabled:
        addon_utils.enable(ADDON, default_set=True, persistent=True)
        print("[live] enabled %s" % ADDON)
    else:
        print("[live] %s already enabled" % ADDON)

    scene = bpy.context.scene
    if hasattr(scene, "blendermcp_port"):
        scene.blendermcp_port = PORT

    # The addon gates its server on the user having accepted its terms, so say
    # so here rather than leaving the port mysteriously shut.
    for flag in ("blendermcp_terms_accepted", "blendermcp_use_polyhaven"):
        if hasattr(scene, flag):
            setattr(scene, flag, True)
            print("[live] set %s" % flag)

    try:
        bpy.ops.blendermcp.start_server()
        print("[live] server listening on %d" % PORT)
    except Exception as exc:                       # noqa: BLE001 - report, never die
        print("[live] could not start the server: %s" % exc)
        print("[live] open the N panel > BlenderMCP > Connect, and it will come up")


if __name__ == "__main__":
    main()
